### ISSUE TITLE
SASS / SCSS Format

### ISSUE THREAD

**Issue by SedueRey** [itmeo/webgradients#3]
Could you create a SCSS format file in order to import it to our projects?

**Comment by alexanderisora** [comment]
Hello @SedueRey !
Some awesome people have already created SCSS,Sass mixins.

But.
WebGradients suddenly became extremely viral. We are under high load, lots of important improvements are in progress. Our team is sleepless (but happy 😅) and very busy.

We will merge all those awesome mixins soon.
Thanks for getting in touch!

**Comment by SedueRey** [comment]
You have did a GREAT work indeed, if you need anything just make me know, I would help you people without any doubt!
